### ISSUE TITLE
v 0.1.1 breaks Kitura-net 0.11.4

### ISSUE THREAD

**Issue by akrabat** [IBM-Swift/CHttpParser#1]
Version 0.1.1 of CHttpParser removes the dependency on the system installed lib-http-parser and brings it "in-house". This means that it creates libCHttpParser.so in my `.build/debug/TestApp` directory.

When I run my app (`./.build/debug/TestApp`), I get:

```
.build/debug/TestApp: error while loading shared libraries: libCHttpParser.so: cannot open shared object file: No such file or directory
```

To resolve, I had to put in a symlink: `sudo ln -s /src/TestApp/.build/debug/libCHttpParser.so /usr/lib/libCHttpParser.so`

How do I avoid this?

**Comment by akrabat** [comment]
I've found a better temporary workaround. In my app's `Package.swift`, I can add:

```
.Package(url: "https://github.com/IBM-Swift/CHttpParser.git", Version(0,1,0)),
```

before

```
.Package(url: "https://github.com/IBM-Swift/Kitura-net.git", majorVersion: 0, minor: 11),
```

And the older version of CHttpParser which depends on the system installed library will be used…

**Comment by shmuelk** [comment]
Actually when building on Linux (which I assume is your case) simply add to your swift build command:

```
-Xlinker -rpath -Xlinker .build/debug
```

Or in otherwords:

   swift build -Xcc -fblocks -Xlinker -rpath -Xlinker .build/debug (plus anything else you need)

The equivalent of this addition is already in the master branch of Swift PAckage Manager, it just hasn't made it to a drop yet.

**Comment by akrabat** [comment]
Aha!. Thanks.
